### PR TITLE
Remove vendored dependencies

### PR DESCRIPTION
**Pull request by bill3tt**
I couldn't think of a good reason why we were vendoring all of our dependencies :shrug: so this PR:
* Removes all of our vendored dependencies
* Removes references to vendoring in Makefile

How do we know this works?
* `make build` completes successfully
* `make container` completes successfully

The integration tests _run_, but I haven't got them to complete successfully yet.

### CODE REVIEW

**Comment by squat** [comment]
It looks like the integration tests are passing successfully in CI. Is it still not working for you?

**Comment by bill3tt** [comment]
Not yet, but pleased CI passes :tada:  Looks like a problem with how the test is orchestrated rather than the binary itself :+1: 

I think the references to `observatorium/observatorium` need updating to `observatorium/api` too :thinking:

**Comment by squat** [comment]
> I think the references to observatorium/observatorium need updating to observatorium/api too thinking

Yes, nice call. Let's go ahead and do this too :)

**Review by onprem — COMMENTED** [review]
LGTM modulo the changes discussed above.

**Review by bwplotka — APPROVED** [review]

**Comment by bill3tt** [comment]
I'll deal with the `observatorium` -> `api` change in a follow-up PR :+1:

**Pull request merged**
